blank_issues_enabled: false
contact_links:
  - name: "Регистрация участника"
    url: https://github.com/Hexlet/hexlet-projects/issues/new?template=registration.md
    about: "Заполни этот шаблон, чтобы зарегистрироваться в проекте."
